### ISSUE TITLE
Fehlende Klammern in deckblatt.tex

### ISSUE THREAD

**Issue by JimmyJ0ee** [gungula/DHBW_LaTeX_template#4]
Heyo :)

Erstmal danke für dein Template, toll kommentiert und somit auch für Newbies einfach zu verstehen. 👍 
Beim Einbinden des Firmenlogos aufs Deckblatt hat mir Latex jedoch angezeigt, dass zu viele Offene Klammern vorhanden sind.
![image](https://github.com/gungula/DHBW_LaTeX_template/assets/98901860/a710994f-9096-4457-b892-754725109dbc)

Ich hab es durch das einfügen von jeweils einer schließenden Klammer in den /iflang ... Zeilen gelöst.
![image](https://github.com/gungula/DHBW_LaTeX_template/assets/98901860/fe773789-24f2-468b-9165-e77b804ef946)

Gib gerne Bescheid, ob das so passt oder ob der Fehler bei mir liegt... 😄 

Viel Erfolg beim Schreiben der Doku!

**Comment by FelixSchladt** [comment]
wurde mit commit 245bce16e253c24b43df940674dc1ac094663fea gefixed!
